package future.response;

public enum ErrorMessage {

	UNAUTHORIZED(401),
	NOT_RECOGNIZED_APP_ID,
	CONFIRMATION_CODE_NOT_FOUND,
	CONFIRMATION_CODE_ALREADY_USED,
	USER_NOT_FOUND(404),
	INVALID_USER_PASSWORD,
	INVALID_OLD_USER_PASSWORD,
	REDIRECTION_CODE_NOT_FOUND,
	REDIRECTION_FAILED,
	CANNOT_GET_REQUIRED_TEMPLATE,
	INTERNAL_ERROR,
	LOGIN_NOT_PROVIDED,
	LOGIN_TOO_SHORT,
	LOGIN_IS_TAKEN,
	PASSWORD_NOT_PROVIDED,
	PASSWORD_IS_TOO_SHORT,
	EMAIL_NOT_PROVIDED,
	INCCORRECT_EMAIL_FORMAT,
	EMAIL_IS_TAKEN,
	LANG_NOT_PROVIDED,
	NOT_RECOGNIZED_LANG_CODE,
	DEFAULT_CURRENCY_NOT_PROVIDED,
	NOT_RECOGNIZED_DEFAULT_CURRENCY,
	HELPLINE_PIN_NOT_PROVIDED,
	HELPLINE_PIN_INCORRECT_LENGTH,
	TOKEN_NOT_FOUND,
	MULTIPLE_TOKENS_WITH_THE_SAME_CODE,
	CLIENT_ID_NOT_PROVIDED,
	FAILED_TO_GENERATE_2FA_TOKEN,
	TWO_FACTOR_TOKEN_ERROR,
	ACCOUNT_ALREADY_CONFIRMED,
	ACCOUNT_TYPE_NOT_PROVIDED,
	ACCOUNT_TYPE_NOT_ALLOWED,
	COMPANY_NAME_NOT_PROVIDED,
	COMPANY_STREET_NOT_PROVIDED,
	COMPANY_POSTAL_CODE_NOT_PROVIDED,
	COMPANY_CITY_NOT_PROVIDED,
	COMPANY_COUNTRY_NOT_PROVIDED,
	COMPANY_NIP_NOT_PROVIDED,
	COMPANY_NIP_INCORRECT,
	COMPANY_DOCUMENTS_SCANS_NOT_PROVIDED,
	FIRST_NAME_NOT_PROVIDED,
	LAST_NAME_NOT_PROVIDED,
	STREET_NOT_PROVIDED,
	POSTAL_CODE_NOT_PROVIDED,
	COUNTRY_NOT_PROVIDED,
	IDENTITY_CARD_NUMBER_NOT_PROVIDED,
	IDENTITY_CARD_ISSUE_DATE_NOT_PROVIDED,
	IDENTITY_CARD_EXPIRATION_DATE_NOT_PROVIDED,
	BIRTH_DATE_NOT_PROVIDED,
	IDENTITY_CARD_SCANS_PROVIDED,
	ADDRESS_CONFIRMATION_SCANS_PROVIDED,
	MARKETING_AGREEMENT_NOT_PROVIDED,
	TWO_FACTOR_METHOD_NOT_PROVIDED,
	ENABLED_NOTIFICATIONS_TYPES_NOT_PROVIDED,
	NOTIFICATION_SOUND_NOT_PROVIDED,
	PHONE_NUMBER_NOT_PROVIDED,
	NOT_RECOGNIZED_TWO_FACTOR_METHOD,
	NO_PERMISSIONS;

	public int code;

	ErrorMessage() {
		code = 400;
	}

	ErrorMessage(int code) {
		this.code = code;
	}
}
